<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\PomoDock.ico</ApplicationIcon>
    <AssemblyName>PomoDock</AssemblyName><Version>0.2.1</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms"/><Using Remove="System.Drawing"/>
    <ProjectReference Include="../PomoDock.Core/PomoDock.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Whisper.net" Version="1.8.1" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.8.1" />
    <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.8.1" />
  </ItemGroup>
</Project>
